name: bun-executable
on:
  push:

jobs:
  compile-and-release:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4.2.2
        
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2.0.2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Start compiling executable
        run: bun build --compile --target=bun-windows-x64 ./index.ts --outfile "Bot Whatsapp Kanigoro.exe"

    #   - name: Sign executable
    #     uses: lando/code-sign-action@v3.0.0
    #     with:
    #       file: "Bot Whatsapp Kanigoro.exe"
    #       certificate-id: ${{ secrets.WINDOZE_CERT_ID }}
    #       certificate-data: ${{ secrets.WINDOZE_CERT_DATA }}
    #       certificate-password: ${{ secrets.WINDOZE_CERT_PASSWORD }}

      - name: Release executable
        uses: softprops/action-gh-release@v2.3.2
        with:
          name: Bot Whatsapp Kanigoro
          files: "Bot Whatsapp Kanigoro.exe"
          tag_name: latest
          make_latest: true